### ISSUE TITLE
Why nuget dependency for DocumentFormat.OpenXml ?

### ISSUE THREAD

**Issue by MaitreDede** [plutext/docx4j.NET#4]
Hi,

I wonder why the docx4j.net has dependency over DocumentFormat.OpenXml ?

Thanks.

**Comment by plutext** [comment]
Because of https://github.com/plutext/docx4j.NET/blob/master/docx4j.NET/src/main/c_sharp/Plutext/Docx4NET/WordprocessingDocumentFactory.cs

(docx4j to OpenXML SDK WordprocessingDocument), and the reverse (ie to docx).

And the equivalents for pptx and xlsx.
